development:
  secret_key_base: 11cb4a9e057cd9bbfa0484ca4110ecb91168570a824a964329a699ca07fd59d4933cfd784389de17c0d28c4d3b6749c07893876a4081170df199b23de42b08b2

test:
  secret_key_base: f63bbdaeae55222c69c5b0a6f141a3d49d2676ff0245ac6e2c7d9d3dc3840456516e02c24f7844a154f713e09fd8c9b14eb36f11c166e00307493be86cf4c3ff

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
